#!/bin/sh

set -eu
#set -x

find_elfs() {
  (
    for f in $(find "$@" -type f -executable); do
      if file $f | grep -q ELF; then
        echo $f
      fi
    done
#  find "$@" -name '*.rlib'
  ) | grep -v 'build.script.build' | sort -u
}

# We try to determine different types of panics (not just calls to core::panicking)

tmp=$(mktemp)

total=0
for f in $(find_elfs "$@"); do
  if echo $f | grep -q '\.rlib'; then
    prefix='R_X86_64_GOTPCREL'
  else
    prefix='\<call'
  fi
  objdump -rd $f | rustfilt | grep "$prefix" > $tmp
  if grep -q 'core::panicking::panic_bounds_check' $tmp; then
    echo >&2 "warning: compiler-generated bounds checks not removed in $f"
  fi
  # See analysis.md for explanation
  explicit_panics=$(grep -c 'core::panicking::panic\(\|_fmt\|_nounwind\|_nounwind_fmt\)\|std::panicking::begin_panic\>' $tmp)
  unwraps=$(grep -c '\(unwrap\|expect\|assert\)_failed' $tmp)
  codegen_checks=$(grep -c 'core::panicking::panic\(_null_pointer_dereference\|_misaligned_pointer_dereference\|_bounds_check\)\>\|slice_.*_fail' $tmp)
  total=$((total + explicit_panics + unwraps + codegen_checks))
done

echo $total

rm -f $tmp
